#! /bin/bash
# This script is meant to evoke the algorithm without requiring any input arguments
#

CONTAINER="[ scitran/dicom-mr-classifier ]"


##############################################################################
# Configure paths

FLYWHEEL_BASE=/flywheel/v0
OUTPUT_DIR=$FLYWHEEL_BASE/output
INPUT_DIR=$FLYWHEEL_BASE/input/dicom
CONFIG_FILE=$FLYWHEEL_BASE/config.json
MANIFEST_FILE=$FLYWHEEL_BASE/manifest.json


##############################################################################
# Parse configuration

if [[ -f $CONFIG_FILE ]]; then
  eval $(jq -r '.config | to_entries[] | "config_\(.key)=\(.value)"' $CONFIG_FILE)
else
  CONFIG_FILE=$MANIFEST_FILE
  eval $(jq -r '.config | to_entries[] | "config_\(.key)=\(.value.default)"' $CONFIG_FILE)
fi


##############################################################################
# Set Time Zone

TZ="${config_timezone}"
echo "${CONTAINER}  Setting time zone to: $TZ"
echo "$TZ" > /etc/timezone && ln -snf /usr/share/zoneinfo/"$TZ" /etc/localtime
dpkg-reconfigure -f noninteractive tzdata


##############################################################################
# Check I/O directories and Generate metadata

# Check that /output directory is empty
if [ "-d" "$OUTPUT_DIR" ]
    then
        if [ "$(ls -A $OUTPUT_DIR)" ]; then
            echo -e "$CONTAINER  Warning $OUTPUT_DIR is not Empty! Results may be overwritten."
        fi
    else
        echo -e "$CONTAINER  $OUTPUT_DIR not found. It will be created."
        mkdir $OUTPUT_DIR
fi


# Check for input
if [[ -z $@ ]]
    then
      input_file=`find $INPUT_DIR -type f -name "*.zip*" | head -1`
      # Check for non-zipped files
      if [[ -z $input_file ]]; then
        input_file=`find $INPUT_DIR -type f -not -path '*/\.*' | head -1`
      fi

      if [[ -n $input_file ]]
        then
            bni=`basename "$input_file"`
            output_file_base=$OUTPUT_DIR/${bni%_dicom.zip}
            PYHONPATH=$PYTHONPATH:/flywheel/v0/ python $FLYWHEEL_BASE/dicom-mr-classifier.py "$input_file" "$output_file_base"
      else
            echo -e "No inputs were provided and $INPUT_DIR has no valid input files!"
            exit 1
      fi
else
    PYHONPATH=$PYTHONPATH:/flywheel/v0/ python $FLYWHEEL_BASE/dicom-mr-classifier.py $@
fi


##############################################################################
# Check for outputs and exit

outputs=`find $OUTPUT_DIR -type f -name ".metadata.json"`

# If outputs exist, then go on...
if [[ -z $outputs ]]
    then
        echo -e "$CONTAINER  No results found in output directory... Exiting"
        exit 1
    else
        chmod -R 777 $OUTPUT_DIR
        echo -e "$CONTAINER  Success."
fi

exit 0
