version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: PIP Install
          command: pip install --user -r tests/requirements.txt
      - run:
          name: Unit Tests
          command: ~/.local/bin/pytest tests/

